### ISSUE TITLE
Failed geocodes results in empty geometry, invalid geojson

### ISSUE THREAD

**Issue by aaronlidman** [tristen/forrest#15]
``` js
     {
      "type": "Feature",
      "geometry": {

      },
      "properties": {
        "Address": "SUPER SECRETZ",
        "City": "ATLANTA",
        "State": "GA",
        "Zip": "30363"
      }
    },
```

Also breaks the map view.

**Comment by tristen** [comment]
Ohhh riiiiggghht. Empty geometries ....

Thanks. I think I'll send the coordinates to null island just on the map if these are empty. The data should update if a marker has been dragged to a new location.

**Comment by tristen** [comment]
Oh ... this would also export invalid geojson. Will fix this.

**Comment by tristen** [comment]
Done in https://github.com/tristen/forrest/commit/20f69a22d030011b90d81f9594283bf3c994706c
